name: bootstrap_italia_example
description: Catalog app showcasing Bootstrap Italia Flutter components.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  bootstrap_italia:
    path: ../

flutter:
  uses-material-design: true
